//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clases
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orden
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orden()
        {
            this.DetallePedido = new HashSet<DetallePedido>();
        }
    
        public int idOrden { get; set; }
        public System.DateTime fechaOrden { get; set; }
        public string estadoOrden { get; set; }
        public string tipoOrden { get; set; }
        public double totalOrden { get; set; }
        public Nullable<int> codCliente { get; set; }
        public Nullable<int> codEmpleado { get; set; }
        public Nullable<int> codMesa { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallePedido> DetallePedido { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Mesa Mesa { get; set; }
    }
}
