//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clases
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public int idVenta { get; set; }
        public Nullable<int> codOrden { get; set; }
        public Nullable<int> codEmpleado { get; set; }
        public string fechaVenta { get; set; }
        public string tipoPago { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Orden Orden { get; set; }
    }
}
